import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });
const Virgil = localFont({ src: './Virgil.woff2' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Virgil.className}>{children}</body>
    </html>
  );
}
